name: device_ui_mode
description: Flutter plugin to get current UI mode of device.
version: 0.0.2
homepage: https://github.com/malviyaritesh/device_ui_mode
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    androidPackage: com.owliverse.device_ui_mode
    pluginClass: DeviceUiModePlugin